#!/usr/bin/env bash

checkpoints=(
"proposition_01"
"proposition_02"
"proposition_03"
"by_prop_CongA_NC"
"lemma_layoffunique"
"proposition_04"
"proposition_05"
"proposition_10"
"proposition_12"
"lemma_planeseparation"
"by_prop_RightTriangle_collinear"
"proposition_07"
"proposition_06"
"proposition_08"
"proposition_09"
"proposition_11"
"proposition_13"
"proposition_14"
"proposition_15"
"proposition_16"
"proposition_17"
"proposition_18"
"proposition_19"
"proposition_20"
"proposition_21"
"proposition_22"
"proposition_23"
"proposition_24"
"lemma_Euclid4"
"proposition_25"
"proposition_26A"
"proposition_27"
"proposition_28A"
"proposition_31"
"proposition_29"
"proposition_30"
"proposition_32"
"proposition_33"
"proposition_34"
"proposition_35"
"proposition_36"
"proposition_37"
"proposition_38"
)

make clean >/dev/null
for checkpoint in "${checkpoints[@]}"; do
	make $checkpoint".glob" | grep -E -v 'COQDEP VFILES' | sed -E 's/COQC //;s/^"coqc".*ProofCheckingEuclid //'
done
